name: desafio_maps
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  rxdart: ^0.23.1
  flutter_modular: ^0.3.4
  cloud_firestore: ^0.13.0+1
  firebase_core: ^0.4.3+2
  flutter_facebook_login: ^3.0.0
  firebase_auth: ^0.15.3+1
  font_awesome_flutter: ^8.5.0
  google_maps_flutter: ^0.5.21+15
  dio: ^3.0.8
  uuid: ^2.0.4
  google_maps_webservice: ^0.0.16
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true